### ISSUE TITLE
Bug with bold parentheses

### ISSUE THREAD

**Issue by kathwill** [hpi-swa-teaching/PowerSqueak#142]
How to reproduce the bug:
- insert text field
- insert text with an opening and a closing paranthesis ('()')

The first parenthesis is written bold.

**Comment by MrModder** [comment]
This also happens when entering code into a browser.
It seems to be default behavior in any Text field to show where the opening parenthesis for the closing parenthesis is.
I don't think this is something you need to concern yourself with as it is behavior that is intended by the system and can actually be quite helpful.
